name: 'Check Fixversion'
on: # rebuild any PRs and main branch changes
  pull_request
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NOT_FOUND_MESSAGE: "Keine Jira Ticket Version angegeben, bitte prüfen!"
          JIRA_ISSUE_REGEX: '.*(TUB-\d+).*'
          JIRA_URL: ${{secrets.JIRA_URL}}
          JIRA_USER: ${{secrets.JIRA_USER}}
          JIRA_PASSWORD: ${{secrets.JIRA_PASSWORD}}
